"""
genderemoticons.py
Nik van 't Slot
s2536420

This program calculates the total occurrences of the heart emoticon and the smile emoticon for both male and female users.
It uses files generated by get-gender.py to determine whether users are male or female.
"""

import sys
import string
from collections import defaultdict

# Define the emoticons. Define every variation of the smile emoticon for complete results
heart = "<3"
smile = {":)", "(:", ":-)", "(-:"}

# Create the counters for all the necessary variables
male_total_tweets = 0
male_heart_tweets = 0
male_smile_tweets = 0
female_total_tweets = 0
female_heart_tweets = 0
female_smile_tweets = 0

# Create a dictionary that records the total usage of the variations of the smile emoticon
total_frequency_dict = defaultdict(int)

for line in sys.stdin:
	smiley = False
	hartje = False
	# If the username corresponds to a male user, activate the counter for male total Tweets
	if line.strip().split("\t")[0].strip() == "male":
		male_total_tweets += 1
		# Strip the Tweet so the emoticons are isolated
		for word in line.strip().split("\t")[2].split():
		    if word in smile:
		    	smiley = True
		    	# Activate the counter for the right variation of the smile emoticon and record the total usage of every variation
		    	total_frequency_dict[word] += 1
		    if word == heart:
		    	hartje = True
		# Activate the right counter if a heart or a smile emoticon has been found in the stripped Tweet
		if smiley:
		    male_smile_tweets += 1

		if hartje:
			male_heart_tweets += 1

        # If the username corresponds to a male user, activate the counter for male total Tweets
	if line.strip().split("\t")[0].strip() == "female":
		female_total_tweets += 1
		# Strip the Tweet so the emoticons are isolated
		for word in line.strip().split("\t")[2].split():
		    if word in smile:
		    	smiley = True
		    	# Activate the counter for the right variation of the smile emoticon and record the total usage of every variation
		    	total_frequency_dict[word] += 1
		    if word == heart:
		    	hartje = True
		# Activate the right counter if a heart or a smile emoticon has been found in the stripped Tweet
		if smiley:
		    female_smile_tweets += 1
		if hartje:
			female_heart_tweets += 1

# Print the results from all the counters
print("{}\t{}".format("Male total tweets:", male_total_tweets))
print("{}\t{}".format("Male smile tweets:", male_smile_tweets))
print("{}\t{}".format("Male heart tweets:", male_heart_tweets))

print("{}\t{}".format("Female total tweets:", female_total_tweets))
print("{}\t{}".format("Female smile tweets:", female_smile_tweets))
print("{}\t{}".format("Female heart tweets:", female_heart_tweets))

# Print the Dictionary containing the totals of every variation of the smile emoticon
print("\nTotal frequency dict:")
print(total_frequency_dict)



